name: E3

on:
  push:
    branches: [main]

jobs:
  e3:
    runs-on: ubuntu-latest
    steps:
      - name: Android SDK
        uses: android-actions/setup-android@v3

      - name: Echo
        run: echo "e3 ok"
